apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfilter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfilter
  template:
    metadata:
      name: myfilter
      labels:
        app: myfilter
    spec:
      containers:
      - name : filter
        image: myapp2
        imagePullPolicy: Never
        env:
        - name: HOST
          value: "kafka.kafka-ca1"
        - name: TIKERS
          value: "bitcoin,ethereum"
        resources:
          limits:
            cpu: 300m
            memory: 20Mi
          requests:
            cpu: 200m
            memory: 10Mi
